project:
  type: website

website:
  title: ""
  google-analytics: 
    tracking-id: G-XPQZQZDK95
  cookie-consent: true
  twitter-card: true
  open-graph: true
  favicon: headshot.jpeg
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: instructional_articles.qmd
        text: Instructional Articles
      - href: resume.qmd
        text: Resume
    right:
      - icon: instagram
        href: https://www.instagram.com/max_sands_7/
      - icon: twitter
        href: https://twitter.com/Max_Sands_7
      - icon: linkedin
        href: https://www.linkedin.com/in/max-sands-1798b41a4/
format:
  html:
    theme: 
      - lux
      - main_style.scss
    css: styles.css
lightbox: true
editor: visual

