---
toc: true
toc-depth: 1
---

[Download My Resume - PDF](files/Max_Sands_Resume.pdf){.btn .btn-primary} [Download My Resume - DOCX](files/Max_Sands_Resume.docx){.btn .btn-primary}

::: panel-tabset
# Education

#### Business Science University

*2022 - Present*

Certified:

-   Data Science for Business w/ R

-   ML & High Performance Time Series Forecasting w/ R

-   Predictive Shiny Web Applications w/ R

-   Shiny Development w/ R & AWS (in progress)

#### McGill University

*2019 - 2022*

Desautels Faculty of Management, Montréal, Canada

Bachelor of Commerce, Major in Finance, Double Concentration in Accounting & Statistics

# Work Experience

#### Choate Hall & Stewart / Choate Investment Advisors

*Business & Investment Analyst* \| *2022 - Present* \| *Boston, MA*

-   Spearheaded data migration project into Addepar - a new system/tool for the Wealth Management Group

    -   Consulted with Partners and all Trust Advisors to gather Ownership Structure data for the entire client base

    -   Used Python to sanitize and properly format all data

-   Built Ad-hoc Dashboards & Reports for Management

    -   Used SQL, Python, R, and Quarto to create Business Intelligence Dashboards & Reports

-   Provided general investment research for the Equity and Fixed Income Teams

    -   Built automated preliminary Investment Analysis report using R and Quarto

        -   By providing a ticker and a list of comps, a report is generated that gathers data from Bloomberg and performs key metric ratio analysis, market share analysis, business segment analysis, etc. to provide a preliminary valuation

-   Developed unique solutions and models for the Investment and Operations divisions:

    -   Built in-house Monte Carlo Simulation tool for client Retirement Analysis

        -   Included sensitivity analysis across several key inputs

        -   Included report generation - both static PDFs and interactive HTML

    -   Built automatic Drift Analysis report using R and Quarto that provides insights on accounts that are drifting off model

        <br>

#### McGill University

*Teaching Assistant* \| *2021 - 2022* \| *Montréal, Canada*

-   Delivering lectures, mentoring/tutoring students, and grading all assessments - typically reserved for Graduate students

    <br>

#### IronHold Capital

*Investment Analyst & Executive Assistant* \| *2020 - 2021* \| *New York, United States*

-   Aided in raising capital, marketing efforts, reviewing legal contracts, and meeting with Family Offices & HNIs on behalf of the CEO

-   Worked directly under the CIO and conducted research on Indian and U.S. Equities - the fund followed a Value-based strategy

-   Author of the fund's newsletter that covered key macroeconomic events, political news, and Family Office industry insights

    <br>

#### Private Tutor

*2018 - 2021*

-   Tutored students in Mathematics, Statistics, Physics, English, and Finance, and revised college admission essays

# Personal Projects

#### Replicating Ray Dalio's Work: Forecasting the 'Big' & 'Debt' Cycles

*2022 - Present*

-   Building a system that continuously retrieves data from various sources and uses Machine Learning to predict several countries' current and future stages of their 'Big' and 'Debt' Cycles, with the eventual goal of predicting asset returns across classes, sectors, and geographies

    <br>

#### Insider Trading - Scraping SEC Form 4 Filings

*2022 - Present*

-   Wrote code in R that scrapes the SEC Edgar site and all of its Form 4 filings. I am currently developing a trading strategy that incorporates this data.

    <br>

#### Coding w/ Bloomberg: Automating Equity Screens & Rough Draft DCFs

*2022*

-   Wrote code in R that connects to and scrapes information from a Bloomberg Terminal by utilizing its Desktop API

    -   Automated Bloomberg's EQS function so that I could run continuous equity screens (i.e. every 'Saturday' since MM/DD/YY)

    -   Used scraped information to automate the generation of a 'rough draft' DCF for any company; companies with a significant discrepancy between 'rough draft' implied share price and 7-day VWAP would garner additional, refined analysis

        <br>

#### Coding w/ Amazon Web Services (AWS), Gemini, & Kraken: Automating Cryptocurrency Trading Strategy

*2022*

-   Wrote code in Python that connects to Gemini (cryptocurrency exchange) web API and allows me to place limit orders if certain conditions are met; automated trading by running the code externally every 5 minutes through AWS Cloudwatch & AWS Lambda

    -   Repeated the above with Kraken (cryptocurrency exchange) web API to place market orders

# Skills & Interests

*Language & Computer Skills:* Fluent French & English, Intermediate Python & R

*Interests:* Financial Analytics/Data Science, Weightlifting, Guitar, Golf, Chess, Poker, Football, Basketball, Math, Creative Writing, Rock Climbing

*Influential Role Models:* Ray Dalio, Andrew Huberman, members of the All-In Podcast
:::